### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by luna533** [jclgoodwin/bustimes.org#242]
Timetable actual time is broken if you select a bus and bus service  the actual time doesn't display however, if you have to bus and it's history, it works that way as included in photos below
![Screenshot_20230823-145628](https://github.com/jclgoodwin/bustimes.org/assets/80555314/35eff06d-d987-4394-b9e7-42e5354928cd)
![Screenshot_20230823-145620](https://github.com/jclgoodwin/bustimes.org/assets/80555314/81d77485-d0b2-49ca-9d91-b25d2e9b1d2e)
![Screenshot_20230823-145614](https://github.com/jclgoodwin/bustimes.org/assets/80555314/535ba090-758b-495b-a8ed-2fcc71cf5812)
![Screenshot_20230823-145606](https://github.com/jclgoodwin/bustimes.org/assets/80555314/952b1e8f-6c45-4ba1-b4a6-bb4c569c9f5b)

**Comment by luna533** [comment]
https://github.com/jclgoodwin/bustimes.org/assets/80555314/6183374e-c30a-4719-82b5-55165e93556f

**Comment by jclgoodwin** [comment]
fixed now (do reopen if you disagree)

**Comment by iMarkeh** [comment]
I think the point being made isn't that something is broken but depending on how you access the trip data, the trip shows up differently. Accessing via clicking vehicle and then clicking the route, this will only show the actual times from 'now'/last tracked point. It also shows the bus livery popup thing showing when it was last updated
If however you click on a vehicle, click the reg and access the trip that way, it will show you all of the past tracking times for that trip. Even if the trip is active, it will only show you the normal arrows, won't show any livery or show last updated (unless you go and click on the arrows). 

Not sure if it would help to save some code to just use the latter rather than the two pages doing the same thing but showing the information differently.

**Comment by jclgoodwin** [comment]
But something *was* broken – nothing was appearing in the trip "Actual" column, and the active trip's vehicle popup wasn't automatically popping up

There's another issue sort of about the thing you describe: https://github.com/jclgoodwin/bustimes.org/issues/139

**Comment by iMarkeh** [comment]
This is how it has been for as long as I can remember. It only shows in the 'actual' column from the point at which you click the page. The user didn't scroll down enough on the page else as the bus would have have an 'actual' time quite low on the page. 

Photos taken a few minutes ago.
First image is if I click the bus then click the route number (all show no times until you go down to where the bus currently is)
Second image is if I click the bus then click the registration and find the same trip.

![Screenshot_20230831-172504](https://github.com/jclgoodwin/bustimes.org/assets/88855038/ef9d7640-c98d-4ea8-9c06-d420b4020e99)
![Screenshot_20230831-172538](https://github.com/jclgoodwin/bustimes.org/assets/88855038/42d27e78-4d91-4dd4-b1ee-13df953ad804)


What we need is the bus tracking location from photo 1 (with the bus popup and livery) but all the actual times from photo 2. Ideally it shouldn't matter how someone accesses the trip, the same information should show.

**Comment by jclgoodwin** [comment]
Yes I know. But the bug described here (I think) meant that **nothing** appeared in the Actual column ever
